// <auto-generated />
using System;
using Innoventity.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innoventity.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InnovationIndustry", b =>
                {
                    b.Property<string>("IndustryId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("InnovationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IndustryId", "InnovationId");

                    b.HasIndex("InnovationId");

                    b.ToTable("InnovationIndustry");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivationToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email", "ActorType")
                        .IsUnique()
                        .HasDatabaseName("IX_Actor_Email_ActorType");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.FormalResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InnovationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ParticipationProposal")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("InnovationId");

                    b.HasIndex("ActorId", "InnovationId")
                        .IsUnique()
                        .HasDatabaseName("IX_FormalResponse_ActorId_InnovationId");

                    b.ToTable("FormalResponses");

                    b.HasDiscriminator<string>("ResponseType").HasValue("FormalResponse");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.Industry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            Id = "HLTH-001",
                            Name = "Health Care"
                        },
                        new
                        {
                            Id = "TECH-001",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = "ENRG-001",
                            Name = "Oil & Gas"
                        },
                        new
                        {
                            Id = "AUTO-001",
                            Name = "Consumer Goods"
                        },
                        new
                        {
                            Id = "INDU-001",
                            Name = "Industrials"
                        },
                        new
                        {
                            Id = "FIN-001",
                            Name = "Financials"
                        },
                        new
                        {
                            Id = "TCOM-001",
                            Name = "Telecommunications"
                        },
                        new
                        {
                            Id = "CSVC-001",
                            Name = "Consumer Services"
                        },
                        new
                        {
                            Id = "UTIL-001",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = "MTRL-001",
                            Name = "Basic Materials"
                        });
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.Innovation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("IdeaToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PartnerSelectionCompletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("SelectedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Innovations");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.InvestorResponse", b =>
                {
                    b.HasBaseType("Innoventity.API.Domain.Entities.FormalResponse");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasDiscriminator().HasValue("InvestorResponse");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.ManufacturingResponse", b =>
                {
                    b.HasBaseType("Innoventity.API.Domain.Entities.FormalResponse");

                    b.HasDiscriminator().HasValue("ManufacturingResponse");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.ResearchDevelopmentResponse", b =>
                {
                    b.HasBaseType("Innoventity.API.Domain.Entities.FormalResponse");

                    b.Property<int>("ProductDevelopmentDuration")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ResearchDevelopmentResponse");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.SalesMarketingResponse", b =>
                {
                    b.HasBaseType("Innoventity.API.Domain.Entities.FormalResponse");

                    b.HasDiscriminator().HasValue("SalesMarketingResponse");
                });

            modelBuilder.Entity("InnovationIndustry", b =>
                {
                    b.HasOne("Innoventity.API.Domain.Entities.Industry", null)
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innoventity.API.Domain.Entities.Innovation", null)
                        .WithMany()
                        .HasForeignKey("InnovationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.Actor", b =>
                {
                    b.OwnsOne("Innoventity.API.Domain.Entities.Address", "ContactAddress", b1 =>
                        {
                            b1.Property<Guid>("ActorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ContactAddress_Address1");

                            b1.Property<string>("Address2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ContactAddress_Address2");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ContactAddress_City");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nchar(2)")
                                .HasColumnName("ContactAddress_CountryCode")
                                .IsFixedLength();

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ContactAddress_PostCode");

                            b1.HasKey("ActorId");

                            b1.ToTable("Actors");

                            b1.WithOwner()
                                .HasForeignKey("ActorId");
                        });

                    b.Navigation("ContactAddress");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.FormalResponse", b =>
                {
                    b.HasOne("Innoventity.API.Domain.Entities.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Innoventity.API.Domain.Entities.Innovation", "Innovation")
                        .WithMany("FormalResponses")
                        .HasForeignKey("InnovationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Innovation");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.Innovation", b =>
                {
                    b.HasOne("Innoventity.API.Domain.Entities.Actor", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Innoventity.API.Domain.Entities.CollaborationRequirement", "CollaborationRequirement", b1 =>
                        {
                            b1.Property<Guid>("InnovationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("PartnersNeeded")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("PartnersNeeded");

                            b1.HasKey("InnovationId");

                            b1.ToTable("Innovations");

                            b1.WithOwner()
                                .HasForeignKey("InnovationId");
                        });

                    b.OwnsOne("Innoventity.API.Domain.Entities.IdeaSummary", "IdeaSummary", b1 =>
                        {
                            b1.Property<Guid>("InnovationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IprStatus")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("IprStatus");

                            b1.Property<string>("ProductType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ProductType");

                            b1.Property<string>("ResearchBackground")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("ResearchBackground");

                            b1.Property<string>("ResearchCategory")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ResearchCategory");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Title");

                            b1.HasKey("InnovationId");

                            b1.ToTable("Innovations");

                            b1.WithOwner()
                                .HasForeignKey("InnovationId");
                        });

                    b.OwnsOne("Innoventity.API.Domain.Entities.Market", "Market", b1 =>
                        {
                            b1.Property<Guid>("InnovationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("PotentialMarketSize")
                                .HasPrecision(28, 2)
                                .HasColumnType("decimal(28,2)")
                                .HasColumnName("PotentialMarketSize");

                            b1.Property<decimal?>("RelevantMarketSize")
                                .HasPrecision(28, 2)
                                .HasColumnType("decimal(28,2)")
                                .HasColumnName("RelevantMarketSize");

                            b1.Property<string>("TargetCustomerBase")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("TargetCustomerBase");

                            b1.Property<string>("TargetCustomerType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("TargetCustomerType");

                            b1.Property<string>("TargetMarket")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("TargetMarket");

                            b1.HasKey("InnovationId");

                            b1.ToTable("Innovations");

                            b1.WithOwner()
                                .HasForeignKey("InnovationId");
                        });

                    b.OwnsOne("Innoventity.API.Domain.Entities.Product", "Product", b1 =>
                        {
                            b1.Property<Guid>("InnovationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AdvantageKeywords")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AdvantageKeywords");

                            b1.Property<string>("DevelopmentPhase")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("DevelopmentPhase");

                            b1.Property<string>("DevelopmentProcess")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("DevelopmentProcess");

                            b1.Property<string>("ProductAdvantages")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("ProductAdvantages");

                            b1.Property<string>("ProductDescription")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("ProductDescription");

                            b1.Property<string>("ProductKeywords")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ProductKeywords");

                            b1.Property<string>("TargetBeneficiaries")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("TargetBeneficiaries");

                            b1.Property<string>("TechnologyDescription")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TechnologyDescription");

                            b1.HasKey("InnovationId");

                            b1.ToTable("Innovations");

                            b1.WithOwner()
                                .HasForeignKey("InnovationId");
                        });

                    b.Navigation("CollaborationRequirement")
                        .IsRequired();

                    b.Navigation("IdeaSummary")
                        .IsRequired();

                    b.Navigation("Market")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.ManufacturingResponse", b =>
                {
                    b.OwnsMany("Innoventity.API.Domain.Entities.YearlyManufacturingCost", "YearlyManufacturingCosts", b1 =>
                        {
                            b1.Property<Guid>("ManufacturingResponseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<decimal>("AverageGlobalDistributionExpense")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("AvgDistributionExpenseRationale")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ProductionVolume")
                                .HasColumnType("int");

                            b1.Property<string>("ProductionVolumeRationale")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("UnitCost")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("UnitCostRationale")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Year")
                                .HasColumnType("int");

                            b1.HasKey("ManufacturingResponseId", "Id");

                            b1.ToTable("FormalResponses");

                            b1.ToJson("YearlyManufacturingCosts");

                            b1.WithOwner()
                                .HasForeignKey("ManufacturingResponseId");
                        });

                    b.Navigation("YearlyManufacturingCosts");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.ResearchDevelopmentResponse", b =>
                {
                    b.OwnsMany("Innoventity.API.Domain.Entities.YearlyDevelopmentCost", "YearlyDevelopmentCosts", b1 =>
                        {
                            b1.Property<Guid>("ResearchDevelopmentResponseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<decimal>("InfrastructureCost")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("InfrastructureCostRationale")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("PeopleCost")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("PeopleCostRationale")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Year")
                                .HasColumnType("int");

                            b1.HasKey("ResearchDevelopmentResponseId", "Id");

                            b1.ToTable("FormalResponses");

                            b1.ToJson("YearlyDevelopmentCosts");

                            b1.WithOwner()
                                .HasForeignKey("ResearchDevelopmentResponseId");
                        });

                    b.Navigation("YearlyDevelopmentCosts");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.SalesMarketingResponse", b =>
                {
                    b.OwnsMany("Innoventity.API.Domain.Entities.YearlySale", "YearlySales", b1 =>
                        {
                            b1.Property<Guid>("SalesMarketingResponseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<decimal>("SalesMarketingExpense")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("SalesMarketingExpenseRationale")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("UnitPriceRationale")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("UnitsSold")
                                .HasColumnType("int");

                            b1.Property<string>("UnitsSoldRationale")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Year")
                                .HasColumnType("int");

                            b1.HasKey("SalesMarketingResponseId", "Id");

                            b1.ToTable("FormalResponses");

                            b1.ToJson("YearlySales");

                            b1.WithOwner()
                                .HasForeignKey("SalesMarketingResponseId");
                        });

                    b.Navigation("YearlySales");
                });

            modelBuilder.Entity("Innoventity.API.Domain.Entities.Innovation", b =>
                {
                    b.Navigation("FormalResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
